config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, :skip => [:sessions]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  as :user do
    get 'user/signin' => 'devise/sessions#new', :as => :new_user_session
    post 'user/signin' => 'devise/sessions#create', :as => :user_session
    get 'user/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root "matches#my"

  # about eaves
  resources :about, only: [:index]
  get '/team', :to => 'about#team', :as => :team
  get '/consent', :to => 'about#consent', :as => :consent

  # matches (配對用)
  resources :matches, only: [:show] do
    collection do
      get :my
      get :my_all
      get :help
      get :help_all
    end
    member do
      post :verify
    end
    resources :comments, only: :index
  end

  #page (問題用)
  resources :pages, except: [:edit, :destroy] do
    collection do
      get :me
      get :me_done
      post :answer
    end
  end

  #Email註冊重複的ajax驗證
  post '/checkemail' => 'users#emailcheck', as: :checkemail


  #以下沒有動

  resources :users, except: [:new, :create, :destroy] do
    member do
      post :exchange_envelope
    end
  end

  # simple_message_system
  resources :conversations do
    resources :messages
  end

  get '/getBasicQuestion', :to => 'matches#getBasicQuestion', :as => :getBasicQuestion  
  post '/postBasicQuestion', :to => 'matches#postBasicQuestion', :as => :postBasicQuestion  
  get '/getAdvancedQuestion', :to => 'matches#getAdvancedQuestion', :as => :getAdvancedQuestion  
  get '/getAnswersHistory', :to => 'matches#getAnswersHistory', :as => :getAnswersHistory  
  post '/postAdvancedQuestion', :to => 'matches#postAdvancedQuestion', :as => :postAdvancedQuestion  
  post '/postAutoEnvelope', :to => 'matches#postAutoEnvelope', :as => :postAutoEnvelope  

  # admin routes
  namespace :admin do
    root "admin/users#index"
    resources :users, only: [:index, :show]
    resources :questions
    resources :answers, only: [:index]
    resources :matches, only: [:index, :show]
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id           :integer          not null, primary key
#  sender_id    :integer
#  recipient_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, scope: :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    if current_user.gender == "Male"
      match_user_ids = Match.where(male_user: current_user, twice: true, status: "EXPIRED").pluck(:female_user_id).uniq
    else
      match_user_ids = Match.where(female_user: current_user, twice: true, status: "EXPIRED").pluck(:male_user_id).uniq
    end
    @users = User.where(id: match_user_ids)
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h3 class="text-info text-center">All Users</h3>
      <% if @users %>
        <% @users.each do |user| %>
          <% if user.id != current_user.id %>
            <div class="row">
              <div class="col-sm-6 offset-sm-3">
                <div class="card" style="width: 18rem;">
                  <div class="card-body text-center">
                    <h5 class="card-title"><%= user.username %></h5>
                    <%= link_to "Message me!", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post, class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-6">
    <h3 class="text-info text-center">Mailbox</h3>
    <div class="row">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <div class="col-sm-6 offset-sm-3 text-center">
            <%= link_to recipient.username, conversation_messages_path(conversation), class: "btn btn-primary" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>