config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, :skip => [:sessions]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  as :user do
    get 'user/signin' => 'devise/sessions#new', :as => :new_user_session
    post 'user/signin' => 'devise/sessions#create', :as => :user_session
    get 'user/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root "matches#my"

  # about eaves
  resources :about, only: [:index]
  get '/team', :to => 'about#team', :as => :team
  get '/consent', :to => 'about#consent', :as => :consent

  # matches (配對用)
  resources :matches, only: [:show] do
    collection do
      get :my
      get :my_all
      get :help
      get :help_all
    end
    member do
      post :verify
    end
    resources :comments, only: :index
  end

  #page (問題用)
  resources :pages, except: [:edit, :destroy] do
    collection do
      get :me
      get :me_done
      post :answer
    end
  end

  #Email註冊重複的ajax驗證
  post '/checkemail' => 'users#emailcheck', as: :checkemail


  #以下沒有動

  resources :users, except: [:new, :create, :destroy] do
    member do
      post :exchange_envelope
    end
  end

  # simple_message_system
  resources :conversations do
    resources :messages
  end

  get '/getBasicQuestion', :to => 'matches#getBasicQuestion', :as => :getBasicQuestion  
  post '/postBasicQuestion', :to => 'matches#postBasicQuestion', :as => :postBasicQuestion  
  get '/getAdvancedQuestion', :to => 'matches#getAdvancedQuestion', :as => :getAdvancedQuestion  
  get '/getAnswersHistory', :to => 'matches#getAnswersHistory', :as => :getAnswersHistory  
  post '/postAdvancedQuestion', :to => 'matches#postAdvancedQuestion', :as => :postAdvancedQuestion  
  post '/postAutoEnvelope', :to => 'matches#postAutoEnvelope', :as => :postAutoEnvelope  

  # admin routes
  namespace :admin do
    root "admin/users#index"
    resources :users, only: [:index, :show]
    resources :questions
    resources :answers, only: [:index]
    resources :matches, only: [:index, :show]
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_comment-backup.html.erb
<div class="comment">
  <p><%= comment.user.username %>說：</p>
  <p><%= comment.content %></p>
  <p>速配指數：<%= comment.score %></p>
</div>

app/views/shared/_date_cover.html.erb
<% #match 輸入一個約會 %>

<div class="carousel-item">
  <div class="card sticky-action" style="overflow: visible;">
    <div class="card-image waves-effect waves-block waves-light">
      <% image="c-00"+(rand(1..8).to_s)+".jpg" #隨機挑一張照片%>
      <%= image_tag image, class: "activator" %>
      <span class="card-title activator text-darken-4">
      <%= match.male_user.username+"與"+match.female_user.username %>
      </span>
    </div>

    <div class="card-action waves-effect" style="width: 100%; cursor: default;">
      <% if target=="match_path" #用來判斷是要驗證約會or約會歷史 %>
        <%= link_to "進入", match_path(match), style: "width: 100%" %>
      <% elsif target=="comment_path" %>
        <%= link_to "進入", match_comments_path(match), style: "width: 100%" %>
      <%end%>
    </div>

  </div>
</div>

app/views/shared/_dating_detail-backup.html.erb
<div class="female_asks pull-left">
  <%= female_user.username%> 問： <%= male_content %>
</div>
<div class="clearfix"></div>
<div class="male_answers pull-right">
  <%= male_user.username%> 回答： <%= male_answer %>
</div>
<div class="male_asks pull-right">
  <%= male_user.username%> 問： <%= female_content %>
</div>
<div class="clearfix"></div>
<div class="female_answers pull-left">
  <%= female_user.username%> 回答： <%= female_answer %>
</div>

app/views/shared/_match-backup.html.erb
<div class="info-body">
  <div class="mb-1 text-muted"><%= (match.dating_datetime + 3.hours).to_s(:short)  %></div>
  <% if match.status == "ACTIVE" %>
  <p class="mb-auto"><%= match.male_user.username %> 和 <%= match.female_user.username %> <%= description %></p>
  <% else %>
  	<% if current_user.gender == "Male" %>
		  <p class="mb-auto">我與 <%= match.female_user.username %> <%= description %></p>
  	<% else %>
  	  <p class="mb-auto">我與 <%= match.male_user.username %> <%= description %></p>
  	<% end %>
  <% end %>
  <%= render partial: "shared/match_links", locals: { match: match, type: match.status } %>
</div>

app/views/shared/_match_links-backup.html.erb
<% if type == "ACTIVE" %>
  <% if current_user.join_comment?(match) %>
    <% if current_user.finish_comment?(match) %>
        <p class="mb-ayto text-right">--(<%= match.verify.comments_count %>/5)已完成評論</p>
        <%= link_to "進入", match_path(match), class: "href-in-info btn btn-outline-success btn-sm" %>
    <% else %>
        <p class="mb-ayto text-right text-danger">--(<%= match.verify.comments_count %>/5)未完成評論</p>
        <%= link_to "進入", match_path(match), class: "href-in-info btn btn-outline-success btn-sm" %>
    <% end %>
  <% else %>
      <p class="mb-ayto text-right">--(<%= match.verify.comments_count %>/5)尚未加入</p>
      <%= link_to "進入", match_path(match), class: "href-in-info btn btn-outline-success btn-sm", data: {confirm: "確定要評論#{match.male_user.username}和#{match.female_user.username}的約會？" } %>
  <% end %>
<% elsif type == "EXPIRED" %>
      <p class="mb-ayto text-right">--共<%= match.verify.comments_count %>則評論</p>
      <%= link_to "進入", match_comments_path(match), class: "href-in-info btn btn-outline-dark btn-sm" %>
<% end %>

app/views/shared/_match_modal-backup.html.erb
<div class="card">
  <div class="card-body">
  	<% if match.status == "ACTIVE" %>
    <h5 class="card-title"><%= match.male_user.username %>  和  <%= match.female_user.username %><%= description %></h5>
    <h6 class="card-subtitle mb-2 text-muted text-right">結束時間：<%= (match.dating_datetime + 3.hours).to_s(:short) %></h6>
    <%= render partial: "shared/match_links", locals: { match: match, type: match.status } %>
    <% else %>
	    <% if current_user.gender == "Male" %>
		    <h5 class="card-title">我與 <%= match.female_user.username %><%= description %></h5>
		    <h6 class="card-subtitle mb-2 text-muted text-right">結束時間：<%= (match.dating_datetime + 3.hours).to_s(:short) %></h6>
		    <%= render partial: "shared/match_links", locals: { match: match, type: match.status } %>
		  <% else %>
		    <h5 class="card-title">我與 <%= match.male_user.username %><%= description %></h5>
		    <h6 class="card-subtitle mb-2 text-muted text-right">結束時間：<%= (match.dating_datetime + 3.hours).to_s(:short) %></h6>
		    <%= render partial: "shared/match_links", locals: { match: match, type: match.status } %>
		  <% end %>
    <% end%>
  </div>
</div>

app/views/shared/_multi_tap_target.html.erb
<a id="<%= tap_name %>_trigger" onclick="tap_<%= tap_name %>_open()">
  <i class="material-icons tap-target-trigger">help</i>
</a>

<a id="<%= tap_name %>" class="waves-effect waves-light btn btn-floating cyan cursor-default" style="opacity: 0;" ><i class="material-icons" style="font-size: 40px">lightbulb_outline</i></a>

<!-- Tap Target Structure -->
<div class="tap-target cyan <%= tap_name %>" data-target="<%= tap_name %>">
  <div class="tap-target-content white-text">
    <h5><%= title %></h5>
    <p><%= content %></p>
  </div>
</div>

<!-- Open Script(Hold other tap targets) -->

<%= javascript_tag do %>

function tap_<%= tap_name %>_open(){
  $('.tap-target').hide();
  $('.tap-target.<%= tap_name %>').show();
  $('.<%= tap_name %>').tapTarget('open');
}

<% end %>

app/views/shared/_tap_target.html.erb
<a  onclick="$('.tap-target').tapTarget('open')">
  <i class="material-icons tap-target-trigger">help</i>
</a>

<a id="info-popup" class="waves-effect waves-light btn btn-floating cyan cursor-default" style="opacity: 0;" ><i class="material-icons" style="font-size: 40px">lightbulb_outline</i></a>

<!-- Tap Target Structure -->
<div class="tap-target cyan" data-target="info-popup">
  <div class="tap-target-content white-text">
    <h5><%= title %></h5>
    <p><%= content %></p>
  </div>
</div>