config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, :skip => [:sessions]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  as :user do
    get 'user/signin' => 'devise/sessions#new', :as => :new_user_session
    post 'user/signin' => 'devise/sessions#create', :as => :user_session
    get 'user/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root "matches#my"

  # about eaves
  resources :about, only: [:index]
  get '/team', :to => 'about#team', :as => :team
  get '/consent', :to => 'about#consent', :as => :consent

  # matches (配對用)
  resources :matches, only: [:show] do
    collection do
      get :my
      get :my_all
      get :help
      get :help_all
    end
    member do
      post :verify
    end
    resources :comments, only: :index
  end

  #page (問題用)
  resources :pages, except: [:edit, :destroy] do
    collection do
      get :me
      get :me_done
      post :answer
    end
  end

  #Email註冊重複的ajax驗證
  post '/checkemail' => 'users#emailcheck', as: :checkemail


  #以下沒有動

  resources :users, except: [:new, :create, :destroy] do
    member do
      post :exchange_envelope
    end
  end

  # simple_message_system
  resources :conversations do
    resources :messages
  end

  get '/getBasicQuestion', :to => 'matches#getBasicQuestion', :as => :getBasicQuestion  
  post '/postBasicQuestion', :to => 'matches#postBasicQuestion', :as => :postBasicQuestion  
  get '/getAdvancedQuestion', :to => 'matches#getAdvancedQuestion', :as => :getAdvancedQuestion  
  get '/getAnswersHistory', :to => 'matches#getAnswersHistory', :as => :getAnswersHistory  
  post '/postAdvancedQuestion', :to => 'matches#postAdvancedQuestion', :as => :postAdvancedQuestion  
  post '/postAutoEnvelope', :to => 'matches#postAutoEnvelope', :as => :postAutoEnvelope  

  # admin routes
  namespace :admin do
    root "admin/users#index"
    resources :users, only: [:index, :show]
    resources :questions
    resources :answers, only: [:index]
    resources :matches, only: [:index, :show]
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  question_id :integer
#  content     :text
#  weight      :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  validates_presence_of(:content,:user_id,:question_id)
  belongs_to :question, optional: true
  belongs_to :user, optional: true
  validates_uniqueness_of :user_id, scope: :question_id

  after_create :answer_question_get_points

  private
  def answer_question_get_points
    self.user.add_points 5
    Notification.create(notify_type: 'add_points', user: self.user, content: "#{self.user.points}")
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  def index
    @ransack = Answer.includes(:question, :user).ransack(params[:q])
    @answers = @ransack.result(distinct: true).page(params[:page]).per(20)
    @answer_count = Answer.count
  end
end

app/helpers/admin/answers_helper.rb
module Admin::AnswersHelper
end

app/views/admin/answers/index.html.erb
<div class="container container-fluid">
  <div class="page-header text-center">
    <h1>Eaves管理後台</h1>
  </div>
  <div class="container-fluid">
    <%= render partial: "admin/shared/navtab" %>
  </div>
  <br>
  <div class="container-fluid">
    <h2>共<%= @answer_count %>筆回答</h2>
    <table id="mytable" class="table table-bordered">
      <thead class="vertical-middle horizontal-center thead-darkgrey">
        <th><%= sort_link @ransack, :id, "ID", default_order: :asc %></th>
        <th><%= sort_link @ransack, :question_title, "題目標題", default_order: :asc %></th>
        <th><%= sort_link @ransack, :user_username, "回答者", default_order: :asc %></th>
        <th style="width: 550px;"><%= sort_link @ransack, :content, "回答內容", default_order: :asc %></th>
        <th>權重</th>
      </thead>
      <tbody>
        <% @answers.each do |answer| %>
          <tr>
            <td><%= answer.id %></td>
            <td><%= link_to answer.question.title, admin_question_path(answer.question)%></td>
            <td><%= answer.user.username %></td>
            <td><%= answer.content %></td>
            <td><%= answer.weight %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="m-auto admin-pagi">
      <%= paginate @answers %>
    </div>
  </div>
</div>