config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, :skip => [:sessions]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  as :user do
    get 'user/signin' => 'devise/sessions#new', :as => :new_user_session
    post 'user/signin' => 'devise/sessions#create', :as => :user_session
    get 'user/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root "matches#my"

  # about eaves
  resources :about, only: [:index]
  get '/team', :to => 'about#team', :as => :team
  get '/consent', :to => 'about#consent', :as => :consent

  # matches (配對用)
  resources :matches, only: [:show] do
    collection do
      get :my
      get :my_all
      get :help
      get :help_all
    end
    member do
      post :verify
    end
    resources :comments, only: :index
  end

  #page (問題用)
  resources :pages, except: [:edit, :destroy] do
    collection do
      get :me
      get :me_done
      post :answer
    end
  end

  #Email註冊重複的ajax驗證
  post '/checkemail' => 'users#emailcheck', as: :checkemail


  #以下沒有動

  resources :users, except: [:new, :create, :destroy] do
    member do
      post :exchange_envelope
    end
  end

  # simple_message_system
  resources :conversations do
    resources :messages
  end

  get '/getBasicQuestion', :to => 'matches#getBasicQuestion', :as => :getBasicQuestion  
  post '/postBasicQuestion', :to => 'matches#postBasicQuestion', :as => :postBasicQuestion  
  get '/getAdvancedQuestion', :to => 'matches#getAdvancedQuestion', :as => :getAdvancedQuestion  
  get '/getAnswersHistory', :to => 'matches#getAnswersHistory', :as => :getAnswersHistory  
  post '/postAdvancedQuestion', :to => 'matches#postAdvancedQuestion', :as => :postAdvancedQuestion  
  post '/postAutoEnvelope', :to => 'matches#postAutoEnvelope', :as => :postAutoEnvelope  

  # admin routes
  namespace :admin do
    root "admin/users#index"
    resources :users, only: [:index, :show]
    resources :questions
    resources :answers, only: [:index]
    resources :matches, only: [:index, :show]
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::BaseController

  before_action :set_match, only: [:show]
  def index
    @ransack  = Match.includes(:male_user, :female_user).ransack(params[:q])
    @matches = @ransack.result(distinct: true).page(params[:page]).per(20)
    @match_count = Match.count
    @status = {'WAITING' => '等待中', 'ACTIVE' => '約會中', 'EXPIRED' => '約會過期'}
  end

  def show
  end

  private

  def set_match
    @match = Match.find(params[:id])
  end

end

app/controllers/matches_controller.rb
class MatchesController < BaseController
  skip_before_action :verify_authenticity_token
  before_action :set_match, only: [:show, :verify, :set_qnagroup]
  before_action :set_qnagroup, only: [:show, :verify]
  after_action :save_my_previous_url, only: [:show]

  #以下新增，邏輯待修正
  def my
    @my_match_numbers = Match.where(male_user_id: current_user.id).or(Match.where(female_user_id: current_user.id)).includes(:male_user, :female_user, :verify).length
    @recent_matches = Match.includes(:male_user, :female_user, :verify)
                        .where.not(male_user_id: current_user.id)
                        .where.not(female_user_id: current_user.id)
                        .order(updated_at: :desc).limit(5)
    @success_matches = Match.expired.where(male_user_id: current_user.id).or(Match.where(female_user_id: current_user.id))
                        .includes(:male_user, :female_user, :verify)
                        .joins(:verify).merge(Verify.where("avg_score >= ?", 60 ))
  end

  def my_all
    @matches = Match.where(male_user_id: current_user.id).or(Match.where(female_user_id: current_user.id)).includes(:male_user, :female_user, :verify)
  end

  def help
    @my_help_matches = Match.where(id: current_user.verifies.pluck(:match_id)).active
    @need_help_matches = Match.active.includes(:male_user, :female_user, :verify)
                .where.not(male_user_id: current_user.id)
                .where.not(female_user_id: current_user.id)
                .joins(:verify).merge(Verify.order("comments_count ASC")) - @my_help_matches
    @matches_count = @my_help_matches.size + @need_help_matches.size
    @need_help_matches = @need_help_matches[0..8]
  end

  def help_all
    @matches = Match.active.includes(:male_user, :female_user, :verify)
                .where.not(male_user_id: current_user.id)
                .where.not(female_user_id: current_user.id)
                .order("created_at ASC")
  end




  #以下沒動
  def index
    #以約會時間快到期與驗證人數未滿篩選出精選約會pick_matches
    @matches = Match.includes(:male_user, :female_user, :verify).where.not(male_user_id: current_user.id).where.not(female_user_id: current_user.id).where(status: "ACTIVE").order("dating_datetime ASC")
               .joins(:verify).merge(Verify.order("comments_count ASC"))
    @pick_matches = @matches.joins(:verify).merge(Verify.where.not(comments_count: 5)).limit(5)
    #挑出約會
    if current_user.gender == "Male"
      @expired_datings = Match.where(male_user: current_user, status: "EXPIRED")
      @recent_datings = @expired_datings.limit(5)
    elsif current_user.gender == "Female"
      @expired_datings = Match.where(female_user: current_user, status: "EXPIRED")
      @recent_datings = @expired_datings.limit(5)
    end

    @status = current_user.check_answered_all_question

    #功能窗格顯示資料使用
    @dated_all_len = @expired_datings.length
    if current_user.gender == "Male"
      @dated_good_len = Match.where(male_user: current_user, status: "EXPIRED").joins(:verify).merge(Verify.where("avg_score >= ?",60)).length
    else
      @dated_good_len = Match.where(female_user: current_user, status: "EXPIRED").joins(:verify).merge(Verify.where("avg_score >= ?",60)).length
    end
    @answered_all_len = Answer.where(user: current_user).length
    if current_user.match_type == "MATCH_FORBID"
      @unanswered_len = Question.where(category: "basic").length-current_user.answered_questions.where(category: "basic").length
    else
      @unanswered_len = current_user.current_questions.length
    end

    #未完成評論連結
    unfinished_comment = current_user.comments.where(content: nil).or(current_user.comments.where(score: nil)).or(current_user.comments.where(content: "")).first
    if unfinished_comment
      @unfinished_match = unfinished_comment.verify.match
    end

  end

  def show
    @other_comments = @match.verify.comments.where.not(user_id: current_user.id, content: nil)
    @back_url = session[:my_previous_url]
    # 檢查此配對是否為約會狀態
    if @match.status != "ACTIVE"
      flash[:alert] = "約會尚未開始或已結束"
      redirect_back(fallback_location: root_path)
      #檢查使用者是否進到自己的評論
    elsif @male_user.id == current_user.id || @female_user.id == current_user.id
      flash[:alert] = "不可評論自己的約會"
      redirect_back(fallback_location: root_path)
        #檢查是否已經評論完畢或者已經加入評論清單，把該筆評論抓出來丟給前端顯示
    elsif current_user.join_comment?(@match)
      @comment = @match.verify.comments.find_by(user_id: current_user.id)
    elsif @match.verify.comments_count == 5
      flash[:alert] = "此約會驗證已滿"
      redirect_back(fallback_location: help_matches_path)
    elsif Match.where(id: current_user.verifies.where("completed_comments_count < ?", 5).pluck(:match_id)).active.size < 5
      @comment = @match.verify.comments.build(user_id: current_user.id)
      @comment.save( validate: false )
    else
      flash[:alert] = "評論約會數量達最大值，請等候其他網友完成評論"
      redirect_to help_matches_path
    end
  end

  def verify
    @comment = current_user.comments.find_by(verify_id: @match.verify.id)
    if @comment.comment_completed?
      if @comment.update(comment_params)
        flash[:notice] = "更新評論"
        redirect_to help_matches_path
      else
        flash.now[:alert] = "內容未填完喔"
        @back_url = session[:my_previous_url]
        @comment = @match.verify.comments.build(comment_params)
        render :show
      end
    else
      if @comment.update(comment_params)
        current_user.add_points 150
        Notification.create(notify_type: 'add_points', user: current_user, content: "#{current_user.points}")
        flash[:notice] = "更新評論"
        redirect_to help_matches_path
      else
        flash.now[:alert] = "內容未填完喔"
        @back_url = session[:my_previous_url]
        @comment = @match.verify.comments.build(comment_params)
        render :show
      end
    end
  end

  def getAnswersHistory
    @user_id = params[:user_id]
    @answers = Answer.where(user_id: @user_id)
    @user = User.find(@user_id)
    @questions = []
    @answers.each do |answer|
      @questions.push(answer.question.title)
    end
    render :json => [@answers, @questions, @user]
  end

  def getBasicQuestion

    @empty_responses = []
    exclude_questions = []
    #取出current_user 所回答的basic類別問題
    current_user.answered_questions.where(category: "basic").each do |q|
      exclude_questions << q.id
    end
    @questions = Question.where(category: "basic").where.not(id: exclude_questions)
    #再用where.not 取出current_user還沒回答過的基本問題

    @gender = User.find(params[:user_id]).gender
    @user_id = params[:user_id]

    render :json => [@questions, @gender, @user_id]

  end

  def postBasicQuestion
    @user_id = params[:user_id]
    @answers = params[:answers]
    @question_ids = params[:question_ids]

    for i in 0...@answers.length
      answer = Answer.new
      answer.user_id = @user_id
      answer.question_id = @question_ids[i]
      answer.content = @answers[i]
      answer.save
    end
  end

   def getAdvancedQuestion

    @empty_responses = []

    def put_in_questions
      if @questions.exists?
        @gender = User.find(params[:user_id]).gender
        @user_id = params[:user_id]
        render :json => ['HAS_QUESTION', @questions, @gender, @user_id]
      else
        render :json => ['NO_NEW_QUESTION']
      end
    end

    if current_user.match_type != "MATCH_FORBID"
    # MATCH FORBID狀態代表未答完基本問題
      @questions = Question.where(id: current_user.current_questions)
      put_in_questions
    else
     render :json => ['BASIC_QUESTION_FIRST']
    end
  end

  def postAdvancedQuestion
    @user_id = params[:user_id]
    @answers = params[:answers]
    @question_ids = params[:question_ids]

    for i in 0...@answers.length
      answer = Answer.new
      answer.user_id = @user_id
      answer.question_id = @question_ids[i]
      answer.content = @answers[i]
      answer.save

      @user = User.find(@user_id)

      @user.current_questions.delete(@question_ids[i].to_i)
      @user.save!

    end
  end

  def postAutoEnvelope
    @user = User.find(params[:user_id])
    @auto_envelope = params[:auto_envelope]
    @user.auto_envelope = @auto_envelope
    @user.save
  end


  private

  def save_my_previous_url
    session[:my_previous_url] = URI(request.referer || '').path
  end

  def set_qnagroup
    # 把Ｑ和Ａ存成ＡＲＲＡＹ再吐給前端處裡
    @qna_groups = []
    @male_user = @match.male_user
    @female_user = @match.female_user
    @questions = Question.where(id: @match.verify.question_ids).order(id: :asc)
    @male_answers = Answer.where(id: @match.verify.male_answers_ids).order(question_id: :asc).pluck(:content)
    @female_answers = Answer.where(id: @match.verify.female_answers_ids).order(question_id: :asc).pluck(:content)
    @questions.each_with_index do |question,index|
      @qna_groups << { question_id: question.id,
                       male_content: question.male_content,
                       female_content: question.female_content,
                       male_answer: @male_answers[index],
                       female_answer: @female_answers[index]
                     }
    end
  end

  def set_match
    @match = Match.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:score, :content)
  end
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/help.html.erb
<div class="pic-panel">
	<%= image_tag "wallpaper.jpg", class: "responsive-img" %>
</div>

<h3 class="div-title">
  熱心民眾
</h3>
<span style="padding-left: 20px; top: -6px;">
  <%= render partial: "shared/tap_target", locals: { title: "說明", content: "(這邊打一些說明)你可以幫助其他人完成約會，這邊會存放你已經完成的約會紀錄，我們會在裡面記錄一些內容"}%>
</span>


<div class="row">
  <div class="col s10 m9">
  	<h5 class="div-title">我正在幫忙的</h5>

    <div class="carousel-outter">
      <div class="slick-1">
        <% if @my_help_matches %>
          <% @my_help_matches.each do |match| %>
            <%= render partial: "shared/date_cover", locals: { match: match, target: "match_path" } %>
          <% end %>
        <% else %>
        <p>目前沒有紀錄</p>
        <% end %>
      </div>
    </div>

    <hr class="center-hr">

		<h5 class="div-title">目前需要幫忙的</h5>

    <div class="carousel-outter">
      <div class="slick-2">
        <% if @need_help_matches %>
          <% @need_help_matches.each do |match| %>
            <%= render partial: "shared/date_cover", locals: { match: match, target: "match_path" } %>
          <% end %>
        <% else %>
        <p>目前沒有紀錄</p>
        <% end %>
      </div>
    </div>



    <hr class="center-hr">
		<p class="sub-title center">目前共有<%= @matches_count %>個約會...
			<%= link_to '(點此看全部)', help_all_matches_path%>
  	</p>
	</div>

	<div class="col s3">
  facebook plug-in
	</div>

</div>

<script>

	// carousel setup
  var slickResponsiveSetting = [
      {
        breakpoint: 1650,
        settings: {
          slidesToShow: 3,
        }
      },
      {
        breakpoint: 1360,
        settings: {
          slidesToShow: 2,
        }
      },
      {
        breakpoint: 1080,
        settings: {
          slidesToShow: 1,
        }
      },
      {
        breakpoint: 992,
        settings: {
          slidesToShow: 2,
        }
      },
      {
        breakpoint: 780,
        settings: {
          slidesToShow: 1,
        }
      }
    ]

  $('.slick-1').slick({
    dots: true,
    speed: 300,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: slickResponsiveSetting,
  });

  $('.slick-2').slick({
    dots: true,
    speed: 300,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: slickResponsiveSetting,
  });

  //nav
  $("#nav-3").addClass('active');

</script>

app/views/matches/help_all.html.erb
<div class="pic-panel">
	<%= image_tag "wallpaper.jpg", class: "responsive-img" %>
</div>

<h3 class="div-title">
  熱心民眾
</h3>
<span style="padding-left: 20px; top: -6px;">
  <%= render partial: "shared/tap_target", locals: { title: "說明", content: "(這邊打一些說明)你可以幫助其他人完成約會，這邊會存放你已經完成的約會紀錄，我們會在裡面記錄一些內容"}%>
</span>

<h5 class="div-title" style="display: block;">
  <%= link_to "回上一頁", :back, {class: "btn"} %>
</h5>

<div class="row">
  <div class="col s10 m9">

		<% @matches.each do |match| %>
      <%= render partial: "shared/date_cover", locals: { match: match, target: "match_path" } %>
    <% end %>

	</div>

	<div class="col s3">
  facebook plug-in
	</div>

</div>

<script>
  $(document).ready(function() {
    $(".carousel-item").css("float","left")
    $(".carousel-item").css("margin-left","20px")
  });

  //nav
  $("#nav-3").addClass('active');
</script>

app/views/matches/my.html.erb
<div class="pic-panel">
	<%= image_tag "wallpaper.jpg", class: "responsive-img" %>
</div>

<h3 class="div-title">
  終結單身
</h3>
<span style="padding-left: 20px; top: -6px;">
  <%= render partial: "shared/multi_tap_target", locals: {tap_name:"main_intro", title: "終結單身", content: "這邊會顯示目前配對的狀態，同時可以看到最近的配對歷史。成功的配對會顯示在最下方，當某個對象成功兩次之後，系統將正式交換雙方資訊，你們便能開始聊天。"}%>
</span>



<div class="row">
  <div class="col s10 m9">

    <div class="dating-info">
      <p>Dashboard</p>
    </div>
    <div class="row dashboard">
      <div class="col s8 l4 dash-element dash-element-circle">
        <div class="circle-wrap">
          <div id="point-circle-0" class="circle"></div>
          <p class="after-circle">當前配對狀態
            <%= render partial: "shared/multi_tap_target", locals: {tap_name:'circle_info_1', title: "配對狀態", content: "當您所填答的題目數量夠時，系統將開始為您安排配對。回答題目越多，也將有助於加速系統配對的效率。"} %>
          </p>
        </div>
      </div>
      <div class="col s8 l4 dash-element dash-element-circle">
        <div class="circle-wrap">
          <div id="point-circle-1" class="circle"></div>
          <p class="after-circle">我的配對經驗
          </p>
        </div>
      </div>
      <div class="col s8 l4 dash-element dash-element-circle">
        <div class="circle-wrap">
          <div id="point-circle-2" class="circle"></div>
          <p class="after-circle">剩餘配對額度
            <%= render partial: "shared/multi_tap_target", locals: {tap_name:'circle_info_3', title: "配對額度", content: "透過幫助他人配對的驗證（熱心民眾）及回答更多題目，可以增加配對額度。當配對額度不足1次時，系統將無法幫您產生新的配對。"} %>
          </p>
        </div>
      </div>
    </div>

  	<h5 class="div-title">最近的約會</h5>

    <div class="carousel-outter">
      <div class="slick-1">
        <% if @resent_matches %>
          <% @resent_matches.each do |match| %>
            <%= render partial: "shared/date_cover", locals: { match: match, target: "comment_path" } %>
          <% end %>
        <% else %>
        <p>目前沒有紀錄</p>
        <% end %>
      </div>
    </div>

    <hr class="center-hr">

		<h5 class="div-title">成功約會紀錄</h5>

    <div class="carousel-outter">
      <div class="slick-2">
        <% if @success_matches %>
          <% @success_matches.each do |match| %>
            <%= render partial: "shared/date_cover", locals: { match: match, target: "comment_path" } %>
          <% end %>
        <% else %>
        <p>目前沒有紀錄</p>
        <% end %>
      </div>
    </div>

    <hr class="center-hr">
		<p class="sub-title center">你共有<%= @my_match_numbers %>個約會...
			<%= link_to '(點此看全部)', my_all_matches_path%>
  	</p>
	</div>

	<div class="col s3">
  facebook plug-in

	</div>

</div>

<%= javascript_tag do %>
  var circle0Text = " ";
  var circle0Num = 33;
  <% if current_user.answers.length < 3 %>
    circle0Text = "<%= "作答數不足"%>";
  <% else %>
    <% if current_user.match_type == "MATCH_ALLOW" %>
      circle0Text = "<%= "系統配對中"%>";
      circle0Num = 66;
    <% else %>
      circle0Text = "<%= "配對驗證中" %>";
      circle0Num = 90;
    <% end %>
  <% end %>
  var circle1Text = "<%= "#{@my_match_numbers}次" %>";
  var circle1Num = <%= @my_match_numbers*10 %>;
  var circle2Text = "<%= "#{current_user.points/100}次" %>";
  var circle2Num = <%= current_user.points/10 %>;
<% end %>

<script>

  // carousel setup
  var slickResponsiveSetting = [
      {
        breakpoint: 1650,
        settings: {
          slidesToShow: 3,
        }
      },
      {
        breakpoint: 1360,
        settings: {
          slidesToShow: 2,
        }
      },
      {
        breakpoint: 1080,
        settings: {
          slidesToShow: 1,
        }
      },
      {
        breakpoint: 992,
        settings: {
          slidesToShow: 2,
        }
      },
      {
        breakpoint: 780,
        settings: {
          slidesToShow: 1,
        }
      }
    ]

  $('.slick-1').slick({
    dots: true,
    speed: 300,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: slickResponsiveSetting,
  });

  $('.slick-2').slick({
    dots: true,
    speed: 300,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: slickResponsiveSetting,
  });

  //nav
  $("#nav-1").addClass('active');

  //circle
  $("#point-circle-0").circliful({
      animationStep: 5,
      foregroundBorderWidth: 5,
      backgroundBorderWidth: 15,
      percent: circle0Num,
      showPercent: 1,
      foregroundColor: "#CD5360",
      replacePercentageByText: circle0Text,
  });
  $("#point-circle-1").circliful({
      animationStep: 5,
      foregroundBorderWidth: 5,
      backgroundBorderWidth: 15,
      percent: circle1Num,
      showPercent: 1,
      foregroundColor: "#008F95",
      replacePercentageByText: circle1Text,
  });
  $("#point-circle-2").circliful({
      animationStep: 5,
      foregroundBorderWidth: 5,
      backgroundBorderWidth: 15,
      percent: circle2Num,
      showPercent: 1,
      foregroundColor: "#94618E",
      replacePercentageByText: circle2Text,
  });


</script>

app/views/matches/my_all.html.erb
<div class="pic-panel">
	<%= image_tag "wallpaper.jpg", class: "responsive-img" %>
</div>

<h3 class="div-title">
  終結單身
</h3>
<span style="padding-left: 20px; top: -6px;">
  <%= render partial: "shared/tap_target", locals: { title: "說明", content: "(這邊打一些說明)你可以幫助其他人完成約會，這邊會存放你已經完成的約會紀錄，我們會在裡面記錄一些內容"}%>
</span>

<h5 class="div-title" style="display: block;">
  <%= link_to "回上一頁", :back, {class: "btn"} %>
</h5>

<div class="row">
  <div class="col s10 m9">

		<% @matches.each do |match| %>
      <%= render partial: "shared/date_cover", locals: { match: match, target: "comment_path" } %>
    <% end %>

	</div>

	<div class="col s3">
  facebook plug-in
	</div>

</div>

<script>
  $(document).ready(function() {
    $(".carousel-item").css("float","left")
    $(".carousel-item").css("margin-left","20px")
  });

  //nav
  $("#nav-1").addClass('active');
</script>

app/views/matches/show-backup.html.erb
<div class="container" id="verify" >
	<div style="height: 1px;"> </div>
  <h2 class="text-center div-title">  <%= @male_user.username %> 和 <%= @female_user.username %> 的約會內容</h2>
	<div class="row">
		<div class="col-sm-4 bubble-box">
			<% @qna_groups.each do |qna| %>
				<div>
					<p style="margin-top: 20px; margin-bottom: 4px;">Q: <%= qna[:female_content] %></p>
				</div>
				<div class="bubble-left" >
					<p><%= qna[:female_answer] %></p>
				</div>
  		<% end %>
		</div>
		<div class="col-sm-4">
			<div class="couple-img-width">
				<div class="couple-img-height">
					<div class="couple-img-position">
						<%= image_tag "couple.png", class: "couple-img-fit" %>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-4 bubble-box">
			<% @qna_groups.each do |qna| %>
				<div>
					<p style="margin-top: 20px; margin-bottom: 4px;">Q: <%= qna[:male_content] %></p>
				</div>
				<div class="bubble-right" >
					<p><%= qna[:male_answer] %></p>
				</div>
  		<% end %>			
		</div>
	</div>
	<div style="padding: 8px 0 ;"><hr class="stylish"></div>
	<h5>給予評論：</h5>
	<div class="">
		<%= form_for(@comment, url: verify_match_path(@match), method: :post, :html => {:class => "verify-form"}) do |f| %>
		  <div class="form-group">
		    <%= f.number_field :score, placeholder: "速配指數？（0-100）", class: "form-control verify-form-input verify-number" %>
		  </div>
		  <div class="form-group">
		    <%= f.text_area :content, placeholder: "中肯的建議，20字以上", class: "form-control verify-form-input verify-text" %>
		  </div>
		  <div class="form-group">
		    <%= link_to "取消", @back_url, class: "btn btn-secondary" %>
		    <%= f.submit "送出", class: "btn btn-primary" %>
		  </div>
		<% end %>
	</div>

	<% if @other_comments %>
		<div style="padding: 8px 0 ;"><hr class="stylish"></div>
		<h5>其他人怎麼說：</h5>
		<div class="row">
			<table class="table">
				<thead>
					<th>#</th>
					<th>Comments</th>
				</thead>
				<tbody>
					<% num = 1 %>
					<% @other_comments.each do |comment| %>
					<tr>
						<td><%= num %></td>
						<td>
							<%= comment.user.username %>說：<%= comment.content %>
							<% num = num + 1 %>
						</td>
					</tr>
	  			<% end %>
				</tbody>
			</table>
		</div>
	<% else %>
		<div class="table-outter">
			<%= image_tag "table.jpg", class: "table-fit" %>
		</div>
	<%end%>



</div>

<script>
$().ready(function() {
  $(".verify-form").validate({
    errorElement: "span",
    success: function(label) {
        label.text(" ").addClass("success");
      },
    highlight: function(element) {
        $(element).css('border-color', '#a94442');
        $(element).next().removeClass("success");
    },
    unhighlight: function(element) {
        $(element).css('border-color', 'green');
    },
    rules: {
      'comment[score]': {
        required: true,
        range:[0,100],
      },
      'comment[content]': {
        required: true,
        minlength: 20,
      },
    },
    })
});
</script>

app/views/matches/show.html.erb
<div class="pic-panel">
	<%= image_tag "wallpaper.jpg", class: "responsive-img" %>
</div>

<h3 class="div-title">
  終結單身
</h3>
<span style="padding-left: 20px; top: -6px;">
  <%= render partial: "shared/tap_target", locals: { title: "說明", content: "(這邊打一些說明)，這邊會存放你已經完成的約會紀錄，我們會在裡面記錄一些內容"}%>
</span>

<h5 class="div-title" style="display: block;">
  <%= link_to "回上一頁", :back, {class: "btn"} %>
</h5>

<div class="row">
  <div class="col s10 m9">

		
		<% @qna_groups.each do |qna| %>
			<div class="girl-box margin-align-center">
				女生問 <%= qna[:male_content] %>
			</div>
			<div class="boy-box margin-align-center" style="margin-bottom: 8px;">
				男生答 <%= qna[:male_answer] %>
			</div>
		<% end %>
  	<hr class="center-hr">
		<% @qna_groups.each do |qna| %>
			<div class="boy-box margin-align-center">
				男生問 <%= qna[:female_content] %>
			</div>
			<div class="girl-box margin-align-center" style="margin-bottom: 8px;">
				女生答 <%= qna[:female_answer] %>
			</div>
		<% end %>

<hr class="center-hr">

		<div class="left-margin" style="padding-bottom:12px;">
		<h5>給予評論：</h5>
		<%= form_for(@comment, url: verify_match_path(@match), method: :post) do |f| %>

		<div class="input-field">
			<p class="verify-input-label">配對分數</p>
			<%= f.number_field :score %>
			<div class="slider-outter">
				<div id="slider"></div>
			</div>
		</div>

		<div class="input-field">
			<p class="verify-input-label">配對意見</p>
		  <%= f.text_area :content, placeholder: "中肯的建議，20字以上", class: "", style: "height: 60px; border: 0.5px solid rgba(0, 0, 0, 0.2); margin-top: 8px;"%>
		</div>
		<div class="input-feild">
			<%= link_to "取消", @back_url, class: "btn" %>
		  <%= f.submit "送出", class: "btn" %>
		</div>
		<% end %>
		</div>

		<div class="left-margin">
		<% if @other_comments %>
			<h5>其他人怎麼說：</h5>
			<table class="striped">
				<thead>
					<th>#</th>
					<th>Comments</th>
				</thead>
				<tbody>
					<% num = 1 %>
					<% @other_comments.each do |comment| %>
					<tr>
						<td><%= num %></td>
						<td>
							<%= comment.user.username %>說：<%= comment.content %>
							<% num = num + 1 %>
						</td>
					</tr>
	  			<% end %>
				</tbody>
			</table>
		<%end%>
		</div>

	</div>

	<div class="col s3">
  facebook plug-in

	</div>

</div>

<script>

  //nav
  $("#nav-1").addClass('active');

	$( document ).ready(function() {

	  //slider
		var slider = document.getElementById('slider');

		noUiSlider.create(slider, {
			start: 60,
			behaviour: 'snap',
			connect: [true, false],
			tooltips: [ true ],
			step: 1,
			range: {
				'min':  0,
				'max':  100
			},
			format: wNumb({
        decimals: 0, // default is 2
    	})
		});

		slider.noUiSlider.set($("#comment_score").val());

		slider.noUiSlider.on("change", function(){
			$("#comment_score").val(slider.noUiSlider.get());
		});

	});

</script>